export const liveMatchesDatas = [
  {
    fixture_id: 1428803,
    country_name: "England",
    elapsed: 49,
    home_team: {
      id: 7726,
      name: "Lancaster City",
      logo: "https://media.api-sports.io/football/teams/7726.png",
      goal: 0,
    },
    away_team: {
      id: 8953,
      name: "Stockton Town",
      logo: "https://media.api-sports.io/football/teams/8953.png",
      goal: 1,
    },
    league: {
      league_id: 59,
      league_name: "Non League Premier - Northern",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1428804,
    country_name: "England",
    elapsed: 48,
    home_team: {
      id: 8822,
      name: "Hebburn Town",
      logo: "https://media.api-sports.io/football/teams/8822.png",
      goal: 2,
    },
    away_team: {
      id: 7695,
      name: "Bamber Bridge",
      logo: "https://media.api-sports.io/football/teams/7695.png",
      goal: 0,
    },
    league: {
      league_id: 59,
      league_name: "Non League Premier - Northern",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1428806,
    country_name: "England",
    elapsed: 48,
    home_team: {
      id: 7663,
      name: "Prescot Cables",
      logo: "https://media.api-sports.io/football/teams/7663.png",
      goal: 0,
    },
    away_team: {
      id: 4691,
      name: "Gainsborough Trinity",
      logo: "https://media.api-sports.io/football/teams/4691.png",
      goal: 1,
    },
    league: {
      league_id: 59,
      league_name: "Non League Premier - Northern",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1428807,
    country_name: "England",
    elapsed: 47,
    home_team: {
      id: 7721,
      name: "Hednesford Town",
      logo: "https://media.api-sports.io/football/teams/7721.png",
      goal: 0,
    },
    away_team: {
      id: 7631,
      name: "Cleethorpes Town",
      logo: "https://media.api-sports.io/football/teams/7631.png",
      goal: 0,
    },
    league: {
      league_id: 59,
      league_name: "Non League Premier - Northern",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1428808,
    country_name: "England",
    elapsed: 47,
    home_team: {
      id: 7236,
      name: "Ilkeston Town",
      logo: "https://media.api-sports.io/football/teams/7236.png",
      goal: 0,
    },
    away_team: {
      id: 7252,
      name: "Stocksbridge Park Steels",
      logo: "https://media.api-sports.io/football/teams/7252.png",
      goal: 0,
    },
    league: {
      league_id: 59,
      league_name: "Non League Premier - Northern",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1429439,
    country_name: "Portugal",
    elapsed: 50,
    home_team: {
      id: 22508,
      name: "Belenenses U19",
      logo: "https://media.api-sports.io/football/teams/22508.png",
      goal: 0,
    },
    away_team: {
      id: 22505,
      name: "Academico Viseu U19",
      logo: "https://media.api-sports.io/football/teams/22505.png",
      goal: 1,
    },
    league: {
      league_id: 1041,
      league_name: "Júniores U19",
      league_logo: "https://media.api-sports.io/flags/pt.svg",
    },
  },
  {
    fixture_id: 1429502,
    country_name: "Portugal",
    elapsed: 48,
    home_team: {
      id: 22520,
      name: "Vitoria Guimaraes U19",
      logo: "https://media.api-sports.io/football/teams/22520.png",
      goal: 0,
    },
    away_team: {
      id: 22517,
      name: "Rio Ave U19",
      logo: "https://media.api-sports.io/football/teams/22517.png",
      goal: 2,
    },
    league: {
      league_id: 1041,
      league_name: "Júniores U19",
      league_logo: "https://media.api-sports.io/flags/pt.svg",
    },
  },
  {
    fixture_id: 1430083,
    country_name: "Switzerland",
    elapsed: 47,
    home_team: {
      id: 12707,
      name: "Muttenz",
      logo: "https://media.api-sports.io/football/teams/12707.png",
      goal: 0,
    },
    away_team: {
      id: 6617,
      name: "Black Stars",
      logo: "https://media.api-sports.io/football/teams/6617.png",
      goal: 1,
    },
    league: {
      league_id: 600,
      league_name: "1. Liga Classic - Group 2",
      league_logo: "https://media.api-sports.io/flags/ch.svg",
    },
  },
  {
    fixture_id: 1430941,
    country_name: "Portugal",
    elapsed: 47,
    home_team: {
      id: 26302,
      name: "União Leiria U19",
      logo: "https://media.api-sports.io/football/teams/26302.png",
      goal: 4,
    },
    away_team: {
      id: 24444,
      name: "Mafra U19",
      logo: "https://media.api-sports.io/football/teams/24444.png",
      goal: 1,
    },
    league: {
      league_id: 1041,
      league_name: "Júniores U19",
      league_logo: "https://media.api-sports.io/flags/pt.svg",
    },
  },
  {
    fixture_id: 1431994,
    country_name: "Spain",
    elapsed: 51,
    home_team: {
      id: 9643,
      name: "Racing Santander II",
      logo: "https://media.api-sports.io/football/teams/9643.png",
      goal: 0,
    },
    away_team: {
      id: 22130,
      name: "Sarriana",
      logo: "https://media.api-sports.io/football/teams/22130.png",
      goal: 0,
    },
    league: {
      league_id: 875,
      league_name: "Segunda División RFEF - Group 1",
      league_logo: "https://media.api-sports.io/flags/es.svg",
    },
  },
  {
    fixture_id: 1434162,
    country_name: "England",
    elapsed: 47,
    home_team: {
      id: 7207,
      name: "Aveley",
      logo: "https://media.api-sports.io/football/teams/7207.png",
      goal: 1,
    },
    away_team: {
      id: 7759,
      name: "Wingate & Finchley",
      logo: "https://media.api-sports.io/football/teams/7759.png",
      goal: 0,
    },
    league: {
      league_id: 58,
      league_name: "Non League Premier - Isthmian",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1435301,
    country_name: "England",
    elapsed: 47,
    home_team: {
      id: 8709,
      name: "Bishop's Cleeve",
      logo: "https://media.api-sports.io/football/teams/8709.png",
      goal: 1,
    },
    away_team: {
      id: 16984,
      name: "Brixham",
      logo: "https://media.api-sports.io/football/teams/16984.png",
      goal: 1,
    },
    league: {
      league_id: 56,
      league_name: "Non League Div One - Southern South",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1435989,
    country_name: "Saudi-Arabia",
    elapsed: 63,
    home_team: {
      id: 2932,
      name: "Al-Hilal Saudi FC",
      logo: "https://media.api-sports.io/football/teams/2932.png",
      goal: 1,
    },
    away_team: {
      id: 2931,
      name: "Al-Fateh",
      logo: "https://media.api-sports.io/football/teams/2931.png",
      goal: 1,
    },
    league: {
      league_id: 307,
      league_name: "Pro League",
      league_logo: "https://media.api-sports.io/flags/sa.svg",
    },
  },
  {
    fixture_id: 1435991,
    country_name: "Saudi-Arabia",
    elapsed: 82,
    home_team: {
      id: 2934,
      name: "Al-Ettifaq",
      logo: "https://media.api-sports.io/football/teams/2934.png",
      goal: 3,
    },
    away_team: {
      id: 2944,
      name: "Al-Fayha",
      logo: "https://media.api-sports.io/football/teams/2944.png",
      goal: 1,
    },
    league: {
      league_id: 307,
      league_name: "Pro League",
      league_logo: "https://media.api-sports.io/flags/sa.svg",
    },
  },
  {
    fixture_id: 1437365,
    country_name: "Saudi-Arabia",
    elapsed: 74,
    home_team: {
      id: 10508,
      name: "Al Jubail",
      logo: "https://media.api-sports.io/football/teams/10508.png",
      goal: 0,
    },
    away_team: {
      id: 2951,
      name: "Abha",
      logo: "https://media.api-sports.io/football/teams/2951.png",
      goal: 3,
    },
    league: {
      league_id: 308,
      league_name: "Division 1",
      league_logo: "https://media.api-sports.io/flags/sa.svg",
    },
  },
  {
    fixture_id: 1443223,
    country_name: "England",
    elapsed: 54,
    home_team: {
      id: 9011,
      name: "Wroxham",
      logo: "https://media.api-sports.io/football/teams/9011.png",
      goal: 0,
    },
    away_team: {
      id: 8965,
      name: "Takeley",
      logo: "https://media.api-sports.io/football/teams/8965.png",
      goal: 0,
    },
    league: {
      league_id: 52,
      league_name: "Non League Div One - Isthmian North",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1443722,
    country_name: "England",
    elapsed: 46,
    home_team: {
      id: 8929,
      name: "Shepshed Dynamo",
      logo: "https://media.api-sports.io/football/teams/8929.png",
      goal: 0,
    },
    away_team: {
      id: 8989,
      name: "Wellingborough Town",
      logo: "https://media.api-sports.io/football/teams/8989.png",
      goal: 0,
    },
    league: {
      league_id: 55,
      league_name: "Non League Div One - Northern Midlands",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1444164,
    country_name: "England",
    elapsed: 46,
    home_team: {
      id: 7676,
      name: "Three Bridges",
      logo: "https://media.api-sports.io/football/teams/7676.png",
      goal: 2,
    },
    away_team: {
      id: 7641,
      name: "Faversham Town",
      logo: "https://media.api-sports.io/football/teams/7641.png",
      goal: 1,
    },
    league: {
      league_id: 57,
      league_name: "Non League Div One - Isthmian South East",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1444166,
    country_name: "England",
    elapsed: 47,
    home_team: {
      id: 8817,
      name: "Hassocks",
      logo: "https://media.api-sports.io/football/teams/8817.png",
      goal: 1,
    },
    away_team: {
      id: 7206,
      name: "Ashford United",
      logo: "https://media.api-sports.io/football/teams/7206.png",
      goal: 3,
    },
    league: {
      league_id: 57,
      league_name: "Non League Div One - Isthmian South East",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1444168,
    country_name: "England",
    elapsed: 46,
    home_team: {
      id: 7249,
      name: "Sevenoaks Town",
      logo: "https://media.api-sports.io/football/teams/7249.png",
      goal: 0,
    },
    away_team: {
      id: 8769,
      name: "Eastbourne Town",
      logo: "https://media.api-sports.io/football/teams/8769.png",
      goal: 0,
    },
    league: {
      league_id: 57,
      league_name: "Non League Div One - Isthmian South East",
      league_logo: "https://media.api-sports.io/flags/gb-eng.svg",
    },
  },
  {
    fixture_id: 1446445,
    country_name: "South-Africa",
    elapsed: 74,
    home_team: {
      id: 26434,
      name: "Leicesterfield",
      logo: "https://media.api-sports.io/football/teams/26434.png",
      goal: 0,
    },
    away_team: {
      id: 2688,
      name: "Baroka FC",
      logo: "https://media.api-sports.io/football/teams/2688.png",
      goal: 0,
    },
    league: {
      league_id: 289,
      league_name: "1st Division",
      league_logo: "https://media.api-sports.io/flags/za.svg",
    },
  },
  {
    fixture_id: 1451512,
    country_name: "Bulgaria",
    elapsed: 50,
    home_team: {
      id: 853,
      name: "CSKA Sofia",
      logo: "https://media.api-sports.io/football/teams/853.png",
      goal: 0,
    },
    away_team: {
      id: 634,
      name: "Botev Plovdiv",
      logo: "https://media.api-sports.io/football/teams/634.png",
      goal: 1,
    },
    league: {
      league_id: 172,
      league_name: "First League",
      league_logo: "https://media.api-sports.io/flags/bg.svg",
    },
  },
];

export const topLeagues = [
  {
    id: 39,
    name: "Premier League",
    flag: "https://media.api-sports.io/flags/gb-eng.svg",
  },
  {
    id: 140,
    name: "La Liga",
    flag: "https://media.api-sports.io/flags/es.svg",
  },
  {
    id: 78,
    name: "Bundesliga",
    flag: "https://media.api-sports.io/flags/de.svg",
  },
  {
    id: 61,
    name: "Ligue 1 (Fransa)",
    flag: "https://media.api-sports.io/flags/fr.svg",
  },
  {
    id: 135,
    name: "Serie A (İtalya)",
    flag: "https://media.api-sports.io/flags/it.svg",
  },
  {
    id: 253,
    name: "Major League Soccer (ABD)",
    flag: "https://media.api-sports.io/flags/us.svg",
  },
  {
    id: 203,
    name: "Süper Lig (Türkiye)",
    flag: "https://media.api-sports.io/flags/tr.svg",
  },
  {
    id: 94,
    name: "Primeira Liga (Portekiz)",
    flag: "https://media.api-sports.io/flags/pt.svg",
  },

  {
    id: 91,
    name: "Eredivisie (Hollanda)",
    flag: "https://media.api-sports.io/flags/nl.svg",
  },

  {
    id: 235,
    name: "Russian Premier League",
    flag: "https://media.api-sports.io/flags/ru.svg",
  },
  {
    id: 145,
    name: "Belgian Pro League",
    flag: "https://media.api-sports.io/flags/be.svg",
  },
  {
    id: 106,
    name: "Ekstraklasa (Polonya)",
    flag: "https://media.api-sports.io/flags/pl.svg",
  },

  {
    id: 2,
    name: "Champions League",
    flag: "https://media.api-sports.io/flags/ua.svg",
  },
  {
    id: 307,
    name: "Saudi Pro League",
    flag: "https://media.api-sports.io/flags/sa.svg",
  },
];


export const seasons = [
  2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
  2023,
];

export const league_info = {
  id: 203,
  league_name: "Süper Lig",
  country: "Turkey",
  logo: "https://media.api-sports.io/football/leagues/203.png",
  season: 2023,
};

export const ranksdata = [
  {
    teams: {
      id: 645,
      rank: 1,
      name: "Galatasaray",
      logo: "https://media.api-sports.io/football/teams/645.png",
      points: 102,
      goalsdiff: 66,
      form: "WLWWW",
      played: 38,
      win: 33,
      draw: 3,
      lose: 2,
    },
  },
  {
    teams: {
      id: 611,
      rank: 2,
      name: "Fenerbahce",
      logo: "https://media.api-sports.io/football/teams/611.png",
      points: 99,
      goalsdiff: 68,
      form: "WWWDW",
      played: 38,
      win: 31,
      draw: 6,
      lose: 1,
    },
  },
  {
    teams: {
      id: 998,
      rank: 3,
      name: "Trabzonspor",
      logo: "https://media.api-sports.io/football/teams/998.png",
      points: 67,
      goalsdiff: 19,
      form: "WWWLW",
      played: 38,
      win: 21,
      draw: 4,
      lose: 13,
    },
  },
  {
    teams: {
      id: 564,
      rank: 4,
      name: "Istanbul Basaksehir",
      logo: "https://media.api-sports.io/football/teams/564.png",
      points: 61,
      goalsdiff: 14,
      form: "WLWWW",
      played: 38,
      win: 18,
      draw: 7,
      lose: 13,
    },
  },
  {
    teams: {
      id: 1004,
      rank: 5,
      name: "Kasimpasa",
      logo: "https://media.api-sports.io/football/teams/1004.png",
      points: 56,
      goalsdiff: -3,
      form: "WDWLW",
      played: 38,
      win: 16,
      draw: 8,
      lose: 14,
    },
  },
  {
    teams: {
      id: 549,
      rank: 6,
      name: "Besiktas",
      logo: "https://media.api-sports.io/football/teams/549.png",
      points: 56,
      goalsdiff: 5,
      form: "LDDWL",
      played: 38,
      win: 16,
      draw: 8,
      lose: 14,
    },
  },
  {
    teams: {
      id: 1002,
      rank: 7,
      name: "Sivasspor",
      logo: "https://media.api-sports.io/football/teams/1002.png",
      points: 54,
      goalsdiff: -7,
      form: "WWLLW",
      played: 38,
      win: 14,
      draw: 12,
      lose: 12,
    },
  },
  {
    teams: {
      id: 996,
      rank: 8,
      name: "Alanyaspor",
      logo: "https://media.api-sports.io/football/teams/996.png",
      points: 52,
      goalsdiff: 3,
      form: "DDDDW",
      played: 38,
      win: 12,
      draw: 16,
      lose: 10,
    },
  },
  {
    teams: {
      id: 1007,
      rank: 9,
      name: "Rizespor",
      logo: "https://media.api-sports.io/football/teams/1007.png",
      points: 50,
      goalsdiff: -10,
      form: "LDLLD",
      played: 38,
      win: 14,
      draw: 8,
      lose: 16,
    },
  },
  {
    teams: {
      id: 1005,
      rank: 10,
      name: "Antalyaspor",
      logo: "https://media.api-sports.io/football/teams/1005.png",
      points: 49,
      goalsdiff: -5,
      form: "DWLLL",
      played: 38,
      win: 12,
      draw: 13,
      lose: 13,
    },
  },
  {
    teams: {
      id: 3573,
      rank: 11,
      name: "Gazişehir Gaziantep",
      logo: "https://media.api-sports.io/football/teams/3573.png",
      points: 44,
      goalsdiff: -7,
      form: "WWWDL",
      played: 38,
      win: 12,
      draw: 8,
      lose: 18,
    },
  },
  {
    teams: {
      id: 3563,
      rank: 12,
      name: "Adana Demirspor",
      logo: "https://media.api-sports.io/football/teams/3563.png",
      points: 44,
      goalsdiff: -7,
      form: "LLLWL",
      played: 38,
      win: 10,
      draw: 14,
      lose: 14,
    },
  },
  {
    teams: {
      id: 3603,
      rank: 13,
      name: "Samsunspor",
      logo: "https://media.api-sports.io/football/teams/3603.png",
      points: 43,
      goalsdiff: -10,
      form: "LDLWL",
      played: 38,
      win: 11,
      draw: 10,
      lose: 17,
    },
  },
  {
    teams: {
      id: 1001,
      rank: 14,
      name: "Kayserispor",
      logo: "https://media.api-sports.io/football/teams/1001.png",
      points: 42,
      goalsdiff: -13,
      form: "LDLDW",
      played: 38,
      win: 11,
      draw: 12,
      lose: 15,
    },
  },
  {
    teams: {
      id: 3575,
      rank: 15,
      name: "Hatayspor",
      logo: "https://media.api-sports.io/football/teams/3575.png",
      points: 41,
      goalsdiff: -7,
      form: "WDWDL",
      played: 38,
      win: 9,
      draw: 14,
      lose: 15,
    },
  },
  {
    teams: {
      id: 607,
      rank: 16,
      name: "Konyaspor",
      logo: "https://media.api-sports.io/football/teams/607.png",
      points: 41,
      goalsdiff: -13,
      form: "LDWDL",
      played: 38,
      win: 9,
      draw: 14,
      lose: 15,
    },
  },
  {
    teams: {
      id: 1010,
      rank: 17,
      name: "Ankaragucu",
      logo: "https://media.api-sports.io/football/teams/1010.png",
      points: 40,
      goalsdiff: -6,
      form: "LDLDD",
      played: 38,
      win: 8,
      draw: 16,
      lose: 14,
    },
  },
  {
    teams: {
      id: 3589,
      rank: 18,
      name: "Fatih Karagümrük",
      logo: "https://media.api-sports.io/football/teams/3589.png",
      points: 40,
      goalsdiff: -3,
      form: "WLLDW",
      played: 38,
      win: 10,
      draw: 10,
      lose: 18,
    },
  },
  {
    teams: {
      id: 3601,
      rank: 19,
      name: "Pendikspor",
      logo: "https://media.api-sports.io/football/teams/3601.png",
      points: 37,
      goalsdiff: -31,
      form: "LDWWL",
      played: 38,
      win: 9,
      draw: 10,
      lose: 19,
    },
  },
  {
    teams: {
      id: 3578,
      rank: 20,
      name: "İstanbulspor",
      logo: "https://media.api-sports.io/football/teams/3578.png",
      points: 16,
      goalsdiff: -53,
      form: "LLLLL",
      played: 38,
      win: 4,
      draw: 7,
      lose: 27,
    },
  },
];

export const topScoresData = [
  {
    player: {
      id: 1100,
      name: "E. Haaland",
      age: 25,
      photo: "https://media.api-sports.io/football/players/1100.png",
    },
    team: {
      id: 50,
      name: "Manchester City",
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    statistics: {
      appearences: 32,
      goal: 27,
    },
  },
  {
    player: {
      id: 152982,
      name: "C. Palmer",
      age: 23,
      photo: "https://media.api-sports.io/football/players/152982.png",
    },
    team: {
      id: 49,
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
    },
    statistics: {
      appearences: 33,
      goal: 22,
    },
  },
  {
    player: {
      id: 2864,
      name: "A. Isak",
      age: 26,
      photo: "https://media.api-sports.io/football/players/2864.png",
    },
    team: {
      id: 34,
      name: "Newcastle",
      logo: "https://media.api-sports.io/football/teams/34.png",
    },
    statistics: {
      appearences: 31,
      goal: 21,
    },
  },
  {
    player: {
      id: 19366,
      name: "O. Watkins",
      age: 30,
      photo: "https://media.api-sports.io/football/players/19366.png",
    },
    team: {
      id: 66,
      name: "Aston Villa",
      logo: "https://media.api-sports.io/football/teams/66.png",
    },
    statistics: {
      appearences: 37,
      goal: 19,
    },
  },
  {
    player: {
      id: 631,
      name: "P. Foden",
      age: 25,
      photo: "https://media.api-sports.io/football/players/631.png",
    },
    team: {
      id: 50,
      name: "Manchester City",
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    statistics: {
      appearences: 37,
      goal: 19,
    },
  },
  {
    player: {
      id: 18883,
      name: "D. Solanke",
      age: 28,
      photo: "https://media.api-sports.io/football/players/18883.png",
    },
    team: {
      id: 35,
      name: "Bournemouth",
      logo: "https://media.api-sports.io/football/teams/35.png",
    },
    statistics: {
      appearences: 38,
      goal: 19,
    },
  },
  {
    player: {
      id: 306,
      name: "Mohamed Salah",
      age: 33,
      photo: "https://media.api-sports.io/football/players/306.png",
    },
    team: {
      id: 40,
      name: "Liverpool",
      logo: "https://media.api-sports.io/football/teams/40.png",
    },
    statistics: {
      appearences: 32,
      goal: 18,
    },
  },
  {
    player: {
      id: 186,
      name: "Son Heung-Min",
      age: 33,
      photo: "https://media.api-sports.io/football/players/186.png",
    },
    team: {
      id: 47,
      name: "Tottenham",
      logo: "https://media.api-sports.io/football/teams/47.png",
    },
    statistics: {
      appearences: 35,
      goal: 17,
    },
  },
  {
    player: {
      id: 19428,
      name: "J. Bowen",
      age: 29,
      photo: "https://media.api-sports.io/football/players/19428.png",
    },
    team: {
      id: 48,
      name: "West Ham",
      logo: "https://media.api-sports.io/football/teams/48.png",
    },
    statistics: {
      appearences: 34,
      goal: 16,
    },
  },
  {
    player: {
      id: 25927,
      name: "J. Mateta",
      age: 28,
      photo: "https://media.api-sports.io/football/players/25927.png",
    },
    team: {
      id: 52,
      name: "Crystal Palace",
      logo: "https://media.api-sports.io/football/teams/52.png",
    },
    statistics: {
      appearences: 35,
      goal: 16,
    },
  },
  {
    player: {
      id: 1460,
      name: "B. Saka",
      age: 24,
      photo: "https://media.api-sports.io/football/players/1460.png",
    },
    team: {
      id: 42,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    statistics: {
      appearences: 35,
      goal: 16,
    },
  },
  {
    player: {
      id: 283058,
      name: "N. Jackson",
      age: 24,
      photo: "https://media.api-sports.io/football/players/283058.png",
    },
    team: {
      id: 49,
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
    },
    statistics: {
      appearences: 35,
      goal: 14,
    },
  },
  {
    player: {
      id: 18931,
      name: "C. Wood",
      age: 34,
      photo: "https://media.api-sports.io/football/players/18931.png",
    },
    team: {
      id: 65,
      name: "Nottingham Forest",
      logo: "https://media.api-sports.io/football/teams/65.png",
    },
    statistics: {
      appearences: 31,
      goal: 14,
    },
  },
  {
    player: {
      id: 978,
      name: "K. Havertz",
      age: 26,
      photo: "https://media.api-sports.io/football/players/978.png",
    },
    team: {
      id: 42,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    statistics: {
      appearences: 37,
      goal: 13,
    },
  },
  {
    player: {
      id: 20649,
      name: "Y. Wissa",
      age: 29,
      photo: "https://media.api-sports.io/football/players/20649.png",
    },
    team: {
      id: 55,
      name: "Brentford",
      logo: "https://media.api-sports.io/football/teams/55.png",
    },
    statistics: {
      appearences: 34,
      goal: 12,
    },
  },
  {
    player: {
      id: 1946,
      name: "L. Trossard",
      age: 31,
      photo: "https://media.api-sports.io/football/players/1946.png",
    },
    team: {
      id: 42,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    statistics: {
      appearences: 34,
      goal: 12,
    },
  },
  {
    player: {
      id: 1165,
      name: "Matheus Cunha",
      age: 26,
      photo: "https://media.api-sports.io/football/players/1165.png",
    },
    team: {
      id: 33,
      name: "Manchester United",
      logo: "https://media.api-sports.io/football/teams/33.png",
    },
    statistics: {
      appearences: 32,
      goal: 12,
    },
  },
  {
    player: {
      id: 24888,
      name: "Hwang Hee-Chan",
      age: 29,
      photo: "https://media.api-sports.io/football/players/24888.png",
    },
    team: {
      id: 39,
      name: "Wolves",
      logo: "https://media.api-sports.io/football/teams/39.png",
    },
    statistics: {
      appearences: 29,
      goal: 12,
    },
  },
  {
    player: {
      id: 51617,
      name: "D. Núñez",
      age: 26,
      photo: "https://media.api-sports.io/football/players/51617.png",
    },
    team: {
      id: 40,
      name: "Liverpool",
      logo: "https://media.api-sports.io/football/teams/40.png",
    },
    statistics: {
      appearences: 36,
      goal: 11,
    },
  },
];